creator: "@Wendy_Bacon"
description: A report on media coverage of climate change in Australia from the Australian Centre for Independent Journalism
keywords: climate change media coverage australia environment journalism
markdown: redcarpet
name: The Australian Centre for Independent Journalism
permalink: pretty
timezone: Australia/Sydney
title: Sceptical Climate
twitter: "@UTSACIJ"
baseurl: "/sceptical-climate/"

